/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.projeto.contratualize.contratualize.view.UserInternalFrames;

import com.projeto.contratualize.contratualize.dao.UserDAO;
import com.projeto.contratualize.contratualize.model.User;
import com.projeto.contratualize.contratualize.util.DeletionConfirmation;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author gabri
 */
public class AllUserScreen extends javax.swing.JInternalFrame {
    UserDAO userDAO = new UserDAO();

    /**
     * Creates new form AllUserScreen
     */
    public AllUserScreen() {
        initComponents();
        loadUsers();

        // Adiciona o MouseListener
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jTable1.rowAtPoint(e.getPoint());
                int column = jTable1.columnAtPoint(e.getPoint());

                if (column == 2) { // Editar
                    String username = (String) jTable1.getValueAt(row, 0);
                    User user = new UserDAO().findByUsername(username);
                    if(user != null) {
                        openEditUserScreen(user);
                    } else {
                        JOptionPane.showMessageDialog(AllUserScreen.this, "Usuário não encontrado.");
                    }
                } else if(column == 3){ //Excluir
                    String username = (String) jTable1.getValueAt(row, 0);
                    if(DeletionConfirmation.userConfirmDeletion(username)){
                        UserDAO userDAO = new UserDAO();
                        User user = userDAO.findByUsername(username);
                        if(user != null){
                            userDAO.delete(user);
                            JOptionPane.showMessageDialog(AllUserScreen.this,"Usuário excluído com sucesso!");
                            loadUsers();
                        } else {
                            JOptionPane.showMessageDialog(AllUserScreen.this, "Usuário não encontrado.");
                        }
                    }
                }
            }
        });
    }
    
    
    
    //Abrir a tela de edição 
    private void openEditUserScreen(User user) {
        EditUserScreen editScreen = new EditUserScreen(user);
        editScreen.setVisible(true);

        // Adiciona ao JDesktopPane
        JDesktopPane desktop = (JDesktopPane) SwingUtilities.getAncestorOfClass(JDesktopPane.class, this);
        if (desktop != null) {
            desktop.add(editScreen);
            editScreen.moveToFront();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao abrir a tela de edição: JDesktopPane não encontrado.");
        }
    }

    private void loadUsers() {
        List<User> users = userDAO.findAll();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (User user : users) {
            model.addRow(new Object[]{
                user.getUsername(),
                user.getRole(),
                "Editar",
                "Excluir"
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setEnabled(false);
        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(502, 450));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuário", "Cargo", "Editar", "Remover"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setAutoscrolls(false);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    
   
    }
