/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.projeto.contratualize.contratualize.view.AlertJInternalFrame;

import com.projeto.contratualize.contratualize.dao.ContractDAO;
import com.projeto.contratualize.contratualize.model.Contract;
import com.projeto.contratualize.contratualize.util.PrescriptionCalculator;
import java.awt.Color;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author gabri
 */
public class AlertScreen extends javax.swing.JInternalFrame {
    
    


    /**
     * Creates new form AlertScreen
     */
    public AlertScreen() {
        initComponents();
        setupDynamicPanel();
        loadAlerts();
        
    }
    
    private void setupDynamicPanel() {
        dynamicPanel = new javax.swing.JPanel();
        dynamicPanel.setLayout(new javax.swing.BoxLayout(dynamicPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(dynamicPanel);
    }
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setResizable(true);
        setVisible(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadAlerts() {
        ContractDAO contractDAO = new ContractDAO();
        List<Contract> contracts = contractDAO.findAll();
        LocalDate currentDate = LocalDate.now();
        for(Contract contract : contracts) {
           LocalDate prescriptionDate = PrescriptionCalculator.calculatePrescriptionDate(contract.getStartDate(), contract.getNumberOfInstallments()); 
           if(ChronoUnit.MONTHS.between(currentDate, prescriptionDate) <= 3) {
               addAlert(contract);
           }
        }
        
    }
    
    public void addAlert(Contract contract) {
        LocalDate currentDate = LocalDate.now();
        LocalDate prescriptionDate = PrescriptionCalculator.calculatePrescriptionDate(contract.getStartDate(), contract.getNumberOfInstallments());
        long daysUntilPrescription = PrescriptionCalculator.getDaysUntilPrescription(prescriptionDate, currentDate);
        
        String timeRemaining;
        if(daysUntilPrescription >= 30) {
            timeRemaining = (daysUntilPrescription / 30) + " meses";
        } else if(daysUntilPrescription >= 7 ){
            timeRemaining = (daysUntilPrescription / 7) + " semanas";
        } else if(daysUntilPrescription >= 1) {
            timeRemaining = daysUntilPrescription + " dias";
        } else {
            timeRemaining = (daysUntilPrescription * 24) + " horas";
        }
        
        JPanel alertPanel = new JPanel();
        alertPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        if(daysUntilPrescription <=0) {
            //alertPanel.setBackground(new java.awt.Color(100, 100, 100));
            alertPanel.setBackground(new java.awt.Color(255, 255, 255));
        }
        else if(daysUntilPrescription <= 7) {
            //alertPanel.setBackground(new java.awt.Color(254, 95, 85));
            alertPanel.setBackground(new java.awt.Color(255, 255, 255));
        } else if(daysUntilPrescription <= 30) {
             alertPanel.setBackground(new java.awt.Color(255, 136, 17));
        } else {
            alertPanel.setBackground(new java.awt.Color(255, 255, 255));
        }
        
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JButton jButton3 = new javax.swing.JButton();
        javax.swing.JToggleButton jToggleButton1 = new javax.swing.JToggleButton();
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-alert-16.png")));
        jLabel1.setText("ALERTA");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13));

        if(daysUntilPrescription <=0) {
            jLabel2.setText("ATENÇÃO!!!");
            jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13));
            
            jLabel3.setText("O CONTRATO " + contract.getContractNumber() + " DO CLIENTE " + contract.getClientName());
            jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13));
            
            jLabel4.setText("PRESCREVEU HÀ " + timeRemaining);
            jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13));
            
            jLabel5.setText("(" + prescriptionDate + ")");
            jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13));
            
            jButton1.setText("REMOVER CONTRATO");
            jButton1.addActionListener(evt -> {
                
            });
            
            jButton3.setText("VER INFORMAÇÕES");
            jButton3.addActionListener(evt -> {

            });
            
            
            jToggleButton1.setText("RESOLVIDO");
            
            
        } else {
            

            jLabel2.setText("ATENÇÃO!!!");
            jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13));


            jLabel3.setText("O CONTRATO " + contract.getContractNumber() + " DO CLIENTE " + contract.getClientName());
            jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13));

            jLabel4.setText("ESTÁ SOB RISCO DE PRESCRIÇÃO EM APROXIMADAMENTE " + timeRemaining);
            jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13));

            jLabel5.setText("(" + prescriptionDate + ")");
            jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13));


            jButton1.setText("VER CONTRATO");
            jButton1.addActionListener(evt -> viewContract(contract));
            
            jButton3.setText("VER INFORMAÇÕES");
            jButton3.addActionListener(evt -> {

            });
            
            
            jToggleButton1.setText("RESOLVIDO");
            

        }
        
       

        // Configurando layout do painel
    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(alertPanel);
    alertPanel.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(30, Short.MAX_VALUE))
    );

    dynamicPanel.add(alertPanel);
    dynamicPanel.revalidate();
    dynamicPanel.repaint();
}
    
    
    
    
    
    private void viewContract(Contract contract) {
        
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel dynamicPanel;
}
